// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import process from "node:process";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "deno run -A prisma/seed.ts",
  },
  datasource: {
    url: "postgresql://postgres:postgres@localhost:5432/classm8_test",
  },
});
